FROM python:3.9-slim

WORKDIR /app
RUN mkdir -p /app/_models

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY classification_model.bin /app/_models/
COPY regression_model.json /app/_models/
COPY *.py /app/

CMD ["uvicorn", "api_model_server:app", "--host", "0.0.0.0", "--port", "8000"]